@startuml
class Agenda {
    -proprietario: String
    +Agenda(proprietario: String)
    +setProprietario(proprietario: String): void
    +getProprietario(): void
    +adicionaContato(c: Contato): void
    +alteraContato(index: int, c: Contato): void
    +excluiContato(index: int): void
    +listarContatos(): String
    +filtrarContatos(): String
}

class Contato {
    -nome: String
    -telefone: String
    -email: String
    -endereco: String
    -cidade: String
    -uf: String
    -cep: String
    -dataNascimento: LocalDate
    +isEmailValid(): boolean
    +toString(): String


}

Agenda "1" --> "1..n" Contato : contém

@enduml
